---
title: "**Informatie over aanvullend onderzoek**"
output: 
  html_document:
    toc: false
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
---
<br>  
  
----

<br>

## 1. Het onderzoek

Voor een aanvullend onderzoeksproject zijn we geïnteresseerd in hoe jij denkt over actuele politieke thema's. Daarom willen we je, net zoals in de eerste vragenlijst, een aantal stellingen voorleggen. We zijn benieuwd in hoeverre jij het met deze stellingen eens of oneens bent. Daarnaast zijn we benieuwd naar wat, volgens jou, de mening is van jouw sociale netwerkleden. We willen deze personen graag ook een soortgelijke vragenlijst voorleggen, van circa 5 minuten. Jij kunt ons helpen door hen de uitnodiging voor de digitiale vragenlijst door te sturen, via e-mail of WhatsApp. 

<br>

## 2. Vergoeding 

We waarderen het enorm als je ons hierbij helpt! Beantwoord jij de extra vragen, stuur je de uitnodigingen rond, en vult ten minste één van je netwerkleden de vragenlijst in? Dan sturen we je nogmaals een 5-euro waardebon (bovenop de waardebon die je sowieso al krijgt)! We zijn er vooral bij gebaat als niet alleen jij, maar ook je netwerkleden de vragen beantwoorden. Daarom zullen we hen ook een 5-euro waardebon sturen nadat zij de vragenlijst hebben voltooid. We zullen in de vragenlijst vragen naar het e-mailadres via welke zij deze vergoeding willen ontvangen.

<br>


## 3. Contactinformatie

Bij vragen, opmerkingen of zorgen over deze studie, kun je contact opnemen met Rob Franken (rob.franken@ru.nl). 


